/**
 * You are given an array of integers "a". A new Array "b" is generated by rearranging
 * the elements of "a" in the following way
 * b[0] is equal to a[0]
 * b[1] is equal to the last element of "a"
 * b[2] is equal to a[1]
 * b[3] is equal to the second-last element of "a"
 * b[4] is equal to a[2]
 * b[5] is equal to the third-last element of "a"
 * and so on.
 * The task is to determine whether the new array "b" is sorted in ascending order or not.
 *  
 */

const buildAndOrder = (a = []) => {
	let min = 0;
	let max = a.length - 1;
	let b = [];
	
	while (b.length < a.length) {
		if (b.length < a.length) {
			b.push(a[min]);
		}
		if (b.length < a.length) {
			b.push(a[max]);
		}
		min++;
		max--;
	}
	return b.every((val, f) => {
		return f === 0 || val >= b[f - 1]
	});
};

module.exports = {
	buildAndOrder,
}